### ISSUE TITLE
Pin length from code

### ISSUE THREAD

**Issue by Savrov** [hendraanggrian/pinview#1]
Hello, thx u for a library. I can't find a method to define pin length from the code (in runtime). Can u add it if not exist, please?

**Comment by hanggrian** [comment]
Right now the width is distributed automatically based on parent's length. But sure, I will add support to it.

**Comment by Savrov** [comment]
@hendraanggrian but I mean the length of pin that I can type. like 1234 or 123456 or 23 or 84353473

**Comment by hanggrian** [comment]
Version 0.2 is out to address this feature. Thanks!
