### ISSUE TITLE
attribute android:pinTextAppearance not found

### ISSUE THREAD

**Issue by Savrov** [hendraanggrian/pinview#2]
Cant build a project, because this property is not defined but is used on demo (in readme)

**Comment by Savrov** [comment]
+ need to update Readme file. 
ex. com.hendraanggrian.PinView -> com.hendraanggrian.appcompat.widget.PinView

**Comment by hanggrian** [comment]
Thanks for the note, I'm on it.

**Comment by hanggrian** [comment]
Use `android:textAppearance` to modify `PinView` text appearance. See [attrs.xml](https://github.com/hendraanggrian/pinview/blob/master/pinview/res/values/attrs.xml) for more.
